version: 2

build:
  apt_packages:
    - inkscape
  tools:
    python: "3.11"

sphinx:
  builder: dirhtml
  configuration: docs/conf.py
  fail_on_warning: true

formats: all

python:
  install:
    - requirements: docs/requirements.txt
